name: Deploy Node Application

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v4
      - name: Login to docker hub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      - name: Build Docker Image
        run: docker build -t fixit24/server --build-arg MONGODB_URI='${{ secrets.MONGODB_URI}}' ./server

      - name: Publish Image to docker hub
        run: docker push fixit24/server:latest

  deploy:
    needs: build
    runs-on: self-hosted
    steps:
      - name: Pull image from docker hub

        run: docker pull fixit24/server:latest
      - name: Delete old container

        run: docker rm -f server-container
      - name: Run Docker Container
        run: docker run -d -p 4000:4000 --name server-container -e SECRET='${{ secrets.SECRET }}' fixit24/server
